config/routes.rb
Rails.application.routes.draw do

  get 'coordinators/settings'
  get 'coordinators/help'
  get 'students/help'

  get 'users/home'

  get 'sessions/new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get 'coordinators/edit_password' => 'coordinators#edit_password', :as => :cedit_password
  patch 'coordinators/update_password' => 'coordinators#update_password', :as => :update_password

  get 'teachers/edit_password' => 'teachers#edit_password'
  patch 'teachers/update_password' => 'teachers#update_password', :as => :update_passwordt

  get 'students/edit_password' => 'students#edit_password'
  patch 'students/update_password' => 'students#update_password', :as => :update_passwords

  get 'users/edit_password' => 'users#edit_password'
  patch 'users/update_password' => 'users#update_password', :as => :update_passwordu
  get 'teachers/profile' => 'teachers#profile'
  get 'students/profile' => 'students#profile'

  get 'coordinators/edit_compexam' => 'coordinators#edit_compexam', :as => :edit_compexam
  patch 'coordinators/update_compexam' => 'coordinators#update_compexam', :as => :update_compexam

  get 'coordinators/add_appearance' => 'coordinators#add_appearance', :as => :add_appearance
  post 'appearance' => 'coordinators#create_appearance'
  get 'coordinators/edit_appearance' => 'coordinators#edit_appearance', :as => :edit_appearance
  patch 'coordinators/update_appearance' => 'coordinators#update_appearance', :as => :update_appearance

  get 'coordinators/discount'
  get 'coordinators/add_discount' => 'coordinators#add_discount', :as => :add_discount
  post 'discount' => 'coordinators#create_discount'
  get 'coordinators/edit_discount' => 'coordinators#edit_discount', :as => :edit_discount
  patch 'coordinators/update_discount' => 'coordinators#update_discount', :as => :update_discount
  get 'coordinators/discount/:id/delete' => 'coordinators#delete_discount'

  get 'coordinators/dashboard'
  get 'coordinators/edit_contpan' => 'coordinators#edit_contpan', :as => :edit_contpan
  patch 'coordinators/edit_contpan' => 'coordinators#update_contpan',:as => :update_contpan
  get 'coordinators/edit_tempval' => 'coordinators#edit_tempval', :as => :edit_tempval
  patch 'coordinators/update_tempval' => 'coordinators#update_tempval', :as => :update_tempval

  get 'coordinators/studentsubjects/:id' => 'coordinators#studentsubjects'
  get 'coordinators/offering'
  get 'coordinators/compexam'

  get 'coordinators/offering/:id/delete' => 'coordinators#delete_offering'

  get 'coordinators/enrollmentdata'
  get 'coordinators/tuition'
  get 'coordinators/roomandfee'
  get 'coordinators/facultyloading'
  #get 'coordinators/:sid/retake/:id' => 'coordinators#retake'

  get 'coordinators/add_retake' => 'coordinators#add_retake', :as => :add_retake
  post 'compexam' => 'coordinators#create_retake', :as => :create_retake

  get 'coordinators/edit_history' => 'coordinators#edit_history', :as => :edit_history
  patch 'coordinators/update_history' => 'coordinators#update_history', :as => :update_history

  get 'coordinators/add_offering' => 'coordinators#add_offering', :as => :add_offering
  post 'offering' => 'coordinators#create_offering'
  get 'coordinators/offering/:id' => 'coordinators#offering_details'
  get 'coordinators/edit_offering' => 'coordinators#edit_offering', :as => :edit_offering
  patch 'coordinators/update_offering' => 'coordinators#update_offering', :as => :update_offering

  get 'coordinators/edit_tfeediscount' => 'coordinators#edit_tfeediscount', :as => :edit_tfeediscount
  patch 'coordinators/update_tfeediscount' => 'coordinators#update_tfeediscount', :as => :update_tfeediscount

  get 'coordinators/edit_roomfee' => 'coordinators#edit_roomfee', :as => :edit_roomfee
  patch 'coordinators/update_roomfee' => 'coordinators#update_roomfee', :as => :update_roomfee
  # programs table
  get 'coordinators/programs'
  get 'coordinators/add_program' => 'coordinators#add_program', :as => :add_program
  post 'programs' => 'coordinators#create_program'
  get 'coordinators/edit_program' => 'coordinators#edit_program', :as => :edit_program
  patch 'coordinators/update_program' => 'coordinators#update_program', :as => :update_program
  get 'coordinators/programs/:id/delete' => 'coordinators#delete_program'
  # specializations
  get 'coordinators/specialization'
  get 'coordinators/add_specialization' => 'coordinators#add_specialization', :as => :add_specialization
  post 'specialization' => 'coordinators#create_specialization'
  get 'coordinators/edit_specialization' => 'coordinators#edit_specialization', :as => :edit_specialization
  patch 'coordinators/update_specialization' => 'coordinators#update_specialization', :as => :update_specialization
  get 'coordinators/specialization/:id/delete' => 'coordinators#delete_specialization'

  get 'coordinators/curriculum'
  get 'coordinators/add_curriculum' => 'coordinators#add_curriculum', :as => :add_curriculum
  post 'curriculum' => 'coordinators#create_curriculum'
  get 'coordinators/edit_curriculum' => 'coordinators#edit_curriculum', :as => :edit_curriculum
  patch 'coordinators/update_curriculum' => 'coordinators#update_curriculum', :as => :update_curriculum
  get 'coordinators/curriculum/:id/delete' => 'coordinators#delete_curriculum'

  get 'coordinators/student'
  get 'coordinators/add_student' => 'coordinators#add_student', :as => :add_student
  post 'student' => 'coordinators#create_student'
  get 'coordinators/edit_student' => 'coordinators#edit_student', :as => :edit_student
  patch 'coordinators/update_student' => 'coordinators#update_student', :as => :update_student
  get 'coordinators/student/:id/delete' => 'coordinators#delete_student'

  get 'coordinators/faculty'
  get 'coordinators/add_faculty' => 'coordinators#add_faculty', :as => :add_faculty
  post 'faculty' => 'coordinators#create_faculty'
  get 'coordinators/edit_faculty' => 'coordinators#edit_faculty', :as => :edit_faculty
  patch 'coordinators/update_faculty' => 'coordinators#update_faculty', :as => :update_faculty
  get 'coordinators/faculty/:id/delete' => 'coordinators#delete_faculty'

  get 'coordinators/subject'
  get 'coordinators/add_subject' => 'coordinators#add_subject', :as => :add_subject
  post 'subject' => 'coordinators#create_subject'
  get 'coordinators/edit_subject' => 'coordinators#edit_subject', :as => :edit_subject
  patch 'coordinators/update_subject' => 'coordinators#update_subject', :as => :update_subject
  get 'coordinators/subject/:id/delete' => 'coordinators#delete_subject'

  get 'coordinators/room'
  get 'coordinators/add_room' => 'coordinators#add_room', :as => :add_room
  post 'room' => 'coordinators#create_room'
  get 'coordinators/edit_room' => 'coordinators#edit_room', :as => :edit_room
  patch 'coordinators/update_room' => 'coordinators#update_room', :as => :update_room
  get 'coordinators/room/:id/delete' => 'coordinators#delete_room'

  get 'coordinators/classtype'
  get 'coordinators/add_classtype' => 'coordinators#add_classtype', :as => :add_classtype
  post 'classtype' => 'coordinators#create_classtype'
  get 'coordinators/edit_classtype' => 'coordinators#edit_classtype', :as => :edit_classtype
  patch 'coordinators/update_classtype' => 'coordinators#update_classtype', :as => :update_classtype
  get 'coordinators/classtype/:id/delete' => 'coordinators#delete_classtype'

  get 'coordinators/fee'
  get 'coordinators/add_fee' => 'coordinators#add_fee', :as => :add_fee
  post 'fee' => 'coordinators#create_fee'
  get 'coordinators/edit_fee' => 'coordinators#edit_fee', :as => :edit_fee
  patch 'coordinators/update_fee' => 'coordinators#update_fee', :as => :update_fee
  get 'coordinators/fee/:id/delete' => 'coordinators#delete_fee'

  get 'coordinators/semester'
  get 'coordinators/add_semester' => 'coordinators#add_semester', :as => :add_semester
  post 'semester' => 'coordinators#create_semester'
  get 'coordinators/edit_semester' => 'coordinators#edit_semester', :as => :edit_semester
  patch 'coordinators/update_semester' =>'coordinators#update_semester', :as => :update_semester
  get 'coordinators/semester/:id/delete' => 'coordinators#delete_semester'

  get 'coordinators/tempsched'
  get 'coordinators/add_tempsched' => 'coordinators#add_tempsched', :as => :add_tempsched
  post 'tempsched' => 'coordinators#create_tempsched'

  get 'coordinators/schoolyear'
  get 'coordinators/add_schoolyear' => 'coordinators#add_schoolyear', :as => :add_schoolyear
  post 'schoolyear' => 'coordinators#create_schoolyear'
  get 'coordinators/edit_schoolyear' => 'coordinators#edit_schoolyear', :as => :edit_schoolyear
  patch 'coordinators/update_schoolyear' => 'coordinators#update_schoolyear', :as => :update_schoolyear

  get 'coordinators/schoolyear'
  get 'coordinators/schoolyear/:id/delete' => 'coordinators#delete_schoolyear'


  get 'coordinators/compexam/student_exam/exam_details/:id' => 'coordinators#exam_details'
  get 'coordinators/compexam'
  get 'coordinators/compexam/student_exams/:id' => 'coordinators#student_exams'
  get 'coordinators/compexam/apply/:id' => 'coordinators#apply', :as => :n_application
  post 'compexamapps' => 'coordinators#create_application', :as => :new_application

  get 'coordinators/compexamapps'
  get 'coordinators/classlist'
  
  get 'coordinators/edit_compexamsubj' => 'coordinators#edit_compexamsubj', :as => :edit_compexamsubj
  patch 'coordinators/update_compexamsubj' => 'coordinators#update_compexamsubj', :as => :update_compexamsubj

  get 'coordinators/enlist'
  get 'coordinators/:id' => 'coordinators#enlist_student', :as => :enlistment
  get 'coordinators/:sid/enlist_subject/:id' => 'coordinators#enlist_subject', :as => :cenlist_subject
  get 'coordinators/:sid/drop/:id' => 'coordinators#drop_subject'

  get 'students/dashboard'
  get 'students/compexam'
  get 'students/compexam/apply' => 'students#apply', :as => :s_application

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :specialization
	belongs_to :curriculum
	has_many :histories, dependent: :destroy
	has_secure_password

	# Line 10-12
	# Validates the stud_id's presence, length with only 9 characters, format,
	# and its uniqueness
	validates :stud_id, presence: true, length: { minimum: 9, maximum: 9 }
	validates_format_of :stud_id, :with => /[0-9]/
	validates :stud_id, :uniqueness => true

	# Line 16-17
	# Validates the s_fname's precence, format, and length with only 1-30 characters
	validates :s_fname, presence: true, length: { minimum: 1, maximum: 30 }
	validates_format_of :s_fname, :multiline => true, :with => /^\A[a-z ]+\z$/i

	# Line 21
	# Validates the s_lname's precence and its length with only 1-30 characters
	validates :s_lname, presence: true, length: { minimum: 1, maximum: 30 }

	# Line 25
	# Validates year, curriculum_id, and specialization_id
	validates :year, :curriculum_id, :specialization_id, :presence => true

	# Line 30-36
	# Capitalizes the first letter oof every word on s_fname, s_mname, and s_lname

	before_save :uppercase_name

	def uppercase_name
		self.s_fname = self.s_fname.split.collect(&:capitalize).join(' ') if self.s_fname && !self.s_fname.blank?
		self.s_mname = self.s_mname.split.collect(&:capitalize).join(' ') if self.s_mname && !self.s_mname.blank?
		self.s_lname = self.s_lname.split.collect(&:capitalize).join(' ') if self.s_lname && !self.s_lname.blank?
	end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_edit_studenthistory.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Edit Discount</h2>
		</div>
		<%= form_for(@history, :url => update_studenthistory_path(:id => params[:id]), :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :discount, "Discount", class: "col-sm-2 control-label" %>
					<% @discount = Discount.all %>
					<div class="col-sm-10">
							<%= f.select(:discount_id, @discount.collect {|disc| [@st = disc.disc_name, disc.id]}, {class: "form-control"}, {id: "select-tag"}) %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">
					<%= f.submit "Update", class: "btn btn-default btn-primary btn-block", :id => "submitform" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/students/_retake_subj.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Retake Subjects</h2>
		</div>
			<%= form_for(@compexam, url: confirm_retake_path, :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :room_name, "Student ID", class: "col-sm-2" %>
					<div class="col-sm-10">
						<div class="">
							<%= @student.stud_id %>
						</div>
					</div>
  				</div>
				<div class="form-group">
					<%= f.label :room_name, "Name", class: "col-sm-2" %>
					<div class="col-sm-10">
						<div class="">
							<%= @student.s_fname %> <%= @student.s_mname %> <%= @student.s_lname %>
						</div>
					</div>
  				</div>
				<div class="form-group">
					<%= f.label :room_name, "Subjects Failed", class: "col-sm-2" %>
					<div class="col-sm-10">
						<% @subj.each do |s| %>
							<% @off = Offering.find(s.offering_id) %>
							<% @subject = Subject.find(@off.subject_id) %>
							<div class="">
								<%= @subject.subject_code %> - <%= @subject.subject_title %>
							</div>
						<% end %>
					</div>
  				</div>
				<div class="form-group">
					<%= f.label :room_name, "OR_NO", class: "col-sm-2" %>
					<div class="col-sm-10">
					<%= f.text_field :or_no, class: "form-control" %>
					</div>
  				</div>  
				<div class="form-group">
					<%= f.label :room_name, "Amount", class: "col-sm-2" %>
					<div class="col-sm-10">
					<%= f.text_field :amount, class: "form-control" %>
					</div>
  				</div>  								
  			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">
					<%= f.submit "Submit", class: "btn btn-default btn-primary btn-block", :id => "submitform" %>
				</div>
			</div>
			<% end %>
	</div>
</div>

app/views/students/apply.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Dashboard
                </li>
                <li class = "active">
                    <span class="glyphicon glyphicon-th"></span>Comprehensive Exam - Application
                </li>
            </ol>
            <div class="panel-heading">
                Application for Comprehensive Exam
            </div>
            <div class="panel-body">
                <%= form_for @compexam, url: "/compexamS", :html => {:class => "form-horizontal"} do |f| %>
                    <%= f.hidden_field :student_id, :value => current_user.id, class: "form-control" %>
                    <% flash.each do |name, msg| %>
                      <div class="alert alert-<%= name %>" role="alert">
                        <b><%= msg %></b>
                        <ul>
                          <li><b>Amount</b> and <b>OR_NO</b> fields are <b>REQUIRED</b>.</li>
                          <li><b>OR_NO</b> may already be <b>TAKEN</b>.</li>
                        </ul>
                      </div>
                    <% end %>
                    <div class="row">
                      <div class="col-md-6">
                        <%= f.label :or_no, "OR_NO" %>
                        <%= f.text_field :or_no, class: "form-control" %>
                      </div>
                      <div class="col-md-6">
                        <%= f.label :amount, "Amount" %>
                        <%= f.text_field :amount, class: "form-control" %>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-md-12">
                        <% @offering = Offering.where(id: @container2) %>

                        <%= f.label :temp, "Please select #{Tempval.first.subjtotake} Subjects" %>
                        <ul class="list-group">
                          <% @offering.each do |o| %>
                            <li class="list-group-item">
                              <div>
                                <%= f.check_box :temp, {:multiple => "true"}, "#{o.id}" %>
                                <% @sem = Semester.find(o.semester_id).sem_name %>
                                <% @styr = Schoolyear.find(o.schoolyear_id).startyr %>
                                <% @enyr = Schoolyear.find(o.schoolyear_id).endyear %>
                                <% @sy = @styr.to_s + "-" + @enyr.to_s %>
                                <% @subjcode = Subject.find(o.subject_id).subject_code %>
                                <% @subjtitle = Subject.find(o.subject_id).subject_title %>
                                <% @subj = @subjcode + "-" + @subjtitle %>
                                <% @fac = Faculty.find(o.faculty_id) %>
                                <% @teacher = @fac.f_fname + " " + @fac.f_mname + " " + @fac.f_lname %>
                                <% @label = @subj + ", " + @sem + " Sem, S/Y " + @sy + ", " + @teacher %>
                                <%= f.label :temp, "#{@label}" %>
                              </div>
                            </li>
                          <% end %>
                        </ul>
                      </div>
                    </div>
                    <center>
                      <button type="button" id="btnapply" class="btn btn-default btn-primary" data-toggle="modal" data-target="#promptSubmit">
                        Submit Application
                      </button>

                      <div id="promptSubmit" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-body">
                              <div class="row">
                                <div class="col-md-9">
                                  <p>Are you sure you want to submit application?</p>
                                </div>
                                <div class="col-md-3">
                                  <button type="button" class="btn btn-default btn-sm pull-right" data-dismiss="modal">NO</button>
                                  <%= f.submit "YES", class: "btn btn-default btn-sm btn-primary" %>
                                </div>
                              </div>
                            </div>
                          </div>

                        </div>
                      </div>
                    </center>
                <% end %>
            </div>
        </div>

        <!-- /.col-lg-12 -->
    </div>
</div>

app/views/students/compexam.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-check"></span>Comprehensive Exam
                </li>
            </ol> 
            <div class="alert alert-dismissable alert-info">
              <strong>Note:</strong>
              Eligibility for taking the comprehensive exam depends on the required minimum number of subjects passed as assigned by the Graduate Program Coordinator
            </div>
            <div class="panel-default panel container-fluid">
                <div class="panel-heading row panel-custom">
                      <div class="col-xs-4">
                          <h3 class="panel-title">My Comprehensive Exams</h3>
                      </div>
                      <div class="col-xs-4"></div>                               
                </div>
                <div class="panel-body">
                    <% @elig = false %>
                    <div class="row">
                        <div class="col-xs-6">
                          Exam Subjects Passed: <%= @passed %>
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-xs-6">
                          <% @verdict %>
                          Result: 
                          <% if @ref != nil %>
                            <% @elig = true %>
                            <% if @checker == true %>
                                  <% @verdict = "PENDING" %>
                                  <span class="label label-warning">PENDING</span>
                            <% elsif @passed < @ref.subjtopass %>
                                  <% @verdict = "FAILED" %>
                                  <span class="label label-danger">FAILED</span>
                            <% elsif @passed >= @ref.subjtopass %>
                                  <% @verdict = "PASSED" %>
                                  <span class="label label-success">PASSED</span>
                            <% end %> 
                          <% end %>                          
                        </div>                    
                    </div>
                    <div class="row">
                      <div class="col-xs-4"></div>
                      <div class="col-xs-6"></div>
                      <div class="col-xs-2"> 
                        <% if @rlog >= Tempval.first.subjtotake && @count == 0 %>
                            <% @elig = true %>
                            <a href="/students/compexam/apply" class="btn btn-primary btn-block" role="button" id="btncommon">New Application</a>
                        <% elsif @verdict == "FAILED" %>
                            <% @elig = true %>
                            <%= button_to('RETAKE', retake_subj_path, {:remote => true, 'data-toggle' => "modal", 'data-target' => '#retake_subj', method: 'get', :class => 'btn btn-sm btn-success pull-right'}) %>                
                        <% end %>  
                      </div>
                    </div>            
                    <br>
            <% if @elig == true %>
              <table class="table table-bordered">
                  <thead>
                    <tr>
                        <th></th>
                        <th>Date Applied</th>
                        <th style="text-align: center">Passing</th>
                        <th style="text-align: center">Score</th>
                        <th style="text-align: center">Amount</th>
                        <th style="text-align: center">OR_NO</th>
                        <th>Result</th>
                        <th style="width: 5%">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @tempcount = 0 %>
                    <% @compexam.each do |c| %>
                        <% @count = Compexamsubj.where(compexam_id: c.id).where(passed: true).count %>
                        <% @test = Compexamsubj.where(compexam_id: c.id).where.not(passed: nil).count %>
                        <% @ver = "N/A" %>

                        <% if @count >= c.subjtopass %>
                            <% @ver = "PASSED" %>
                        <% elsif @count < c.subjtopass && @test == c.subjtotake %>
                            <% @ver = "FAILED" %>
                        <% end %>
                        <tr>
                            <td style="text-align: center"><%= @tempcount = @tempcount + 1 %></td>
                            <td><%= c.date_applied.strftime("%a, %b %d, %Y")  %></td>
                            <td><%= c.subjtopass %>/<%= c.subjtotake %></td>
                            <td><%= @count %></td>
                            <td><%= c.amount %></td>
                            <td><%= c.or_no %></td>
                            <td style="text-align: center">
                                <% if @ver == "PASSED" %>
                                    <span class="label label-success">PASSED</span>
                                <% elsif @ver == "FAILED" %>
                                    <span class="label label-danger">FAILED</span>
                                <% else %>
                                    <span class="label label-warning">PENDING
                                <% end %>
                                </td>
                            <td>
                              <a class="btn btn-sm btn-primary" href="/students/compexam/<%= c.id %>"><span class="glyphicon glyphicon-eye-open"></span></a>
                            </td>
                        </tr>
                    <% end %>
                  </tbody>
              </table>
            <% else %>
              <div style="color: red!important">
                <h4>
                  <b>YOU ARE NOT ELIGIBLE TO TAKE THE COMPREHENSIVE EXAM</b>
                </h4>
                <h4>
                  <b>FOR CONCERNS, PLEASE CONTACT THE GRADUATE PROGRAM COORDINATOR</b>
                </h4>
              </div>
            <% end %>                                  
                </div>            
            </div>         
        </div>

        <!-- /.col-lg-12 -->
    </div>
</div>
<div id="retake_subj" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/students/dashboard.html.erb
<div id="page-wrapper">
    <div class="row">
      <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Dashboard
                </li>
            </ol>
        <div class="row">
          <div class="col-md-12">
          <div id="myCarousel" class="carousel slide">
            <!-- Carousel indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

                <!-- Carousel items -->
                <div class="carousel-inner">
                        <div class="active item">
                              <%=  link_to image_tag("carousel1.jpg", :alt => "Slide1", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                        <div class="item">
                              <%=  link_to image_tag("carousel2.jpg", :alt => "Slide2", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                        <div class="item">
                              <%=  link_to image_tag("carousel3.jpg", :alt => "Slide3", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                        <div class="item">
                              <%=  link_to image_tag("carousel4.jpg", :alt => "Slide4", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                </div>
                <!-- Carousel nav -->
                <a class="carousel-control left" href="#myCarousel" data-slide="prev"></a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next"></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(function(){
  $('#myCarousel').carousel('cycle');
});
</script>

app/views/students/edit_password.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Dashboard
                </li>
                <li class = "">
                    <span class="glyphicon glyphicon-th"></span>Change Password
                </li>
            </ol>
            <div class="row">
                <div class="col-md-9">
                    <div class="panel-heading custompanel">
                      <h4 class="semibold nm">CHANGE PASSWORD</h4>
                    </div>
                    <div class="panel-body">
                        <%= form_for(@student, :url => update_passwords_path) do |f| %>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "Old Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= password_field_tag :current_password, params[:current_password] %>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "New Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= f.password_field :password %>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "Confirm Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= f.password_field :password_confirmation %>
                              </div>
                          </div>
                            <div class="col-sm-6">
                              <%= f.submit "Update Password", class: "btn btn-info btm-sm" %>
                            </div>
                        <% end %>                        
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

app/views/students/edit_studenthistory.js.erb
$(document).ready( function() {
	$("#edit_studenthistory").html("<%= escape_javascript(render 'students/edit_studenthistory') %>");
	$('#edit_studenthistory').modal('show');

	$("#select-tag").select2({
    minimumResultsForSearch: -1,
		width: "95%"
  });
});

$("#submitform").click( function() {
  $( '#edit_studenthistory' ).modal( 'hide' );
});

$('#edit_studenthistory').on('hidden.bs.modal', function () {
	setTimeout('history.go(0);');
})

app/views/students/retake_subj.js.erb
$(document).ready( function() {
	$("#retake_subj").html("<%= escape_javascript(render 'students/retake_subj') %>");
	$('#retake_subj').modal('show');
});

$("#submitform").click( function() {
  $( '#retake_subj' ).modal( 'hide' );
});

$('#retake_subj').on('hidden.bs.modal', function () {
	setTimeout('history.go(0);');
})