config/routes.rb
Rails.application.routes.draw do

  get 'coordinators/settings'
  get 'coordinators/help'
  get 'students/help'

  get 'users/home'

  get 'sessions/new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get 'coordinators/edit_password' => 'coordinators#edit_password', :as => :cedit_password
  patch 'coordinators/update_password' => 'coordinators#update_password', :as => :update_password

  get 'teachers/edit_password' => 'teachers#edit_password'
  patch 'teachers/update_password' => 'teachers#update_password', :as => :update_passwordt

  get 'students/edit_password' => 'students#edit_password'
  patch 'students/update_password' => 'students#update_password', :as => :update_passwords

  get 'users/edit_password' => 'users#edit_password'
  patch 'users/update_password' => 'users#update_password', :as => :update_passwordu
  get 'teachers/profile' => 'teachers#profile'
  get 'students/profile' => 'students#profile'

  get 'coordinators/edit_compexam' => 'coordinators#edit_compexam', :as => :edit_compexam
  patch 'coordinators/update_compexam' => 'coordinators#update_compexam', :as => :update_compexam

  get 'coordinators/add_appearance' => 'coordinators#add_appearance', :as => :add_appearance
  post 'appearance' => 'coordinators#create_appearance'
  get 'coordinators/edit_appearance' => 'coordinators#edit_appearance', :as => :edit_appearance
  patch 'coordinators/update_appearance' => 'coordinators#update_appearance', :as => :update_appearance

  get 'coordinators/discount'
  get 'coordinators/add_discount' => 'coordinators#add_discount', :as => :add_discount
  post 'discount' => 'coordinators#create_discount'
  get 'coordinators/edit_discount' => 'coordinators#edit_discount', :as => :edit_discount
  patch 'coordinators/update_discount' => 'coordinators#update_discount', :as => :update_discount
  get 'coordinators/discount/:id/delete' => 'coordinators#delete_discount'

  get 'coordinators/dashboard'
  get 'coordinators/edit_contpan' => 'coordinators#edit_contpan', :as => :edit_contpan
  patch 'coordinators/edit_contpan' => 'coordinators#update_contpan',:as => :update_contpan
  get 'coordinators/edit_tempval' => 'coordinators#edit_tempval', :as => :edit_tempval
  patch 'coordinators/update_tempval' => 'coordinators#update_tempval', :as => :update_tempval

  get 'coordinators/studentsubjects/:id' => 'coordinators#studentsubjects'
  get 'coordinators/offering'
  get 'coordinators/compexam'

  get 'coordinators/offering/:id/delete' => 'coordinators#delete_offering'

  get 'coordinators/enrollmentdata'
  get 'coordinators/tuition'
  get 'coordinators/roomandfee'
  get 'coordinators/facultyloading'
  #get 'coordinators/:sid/retake/:id' => 'coordinators#retake'

  get 'coordinators/add_retake' => 'coordinators#add_retake', :as => :add_retake
  post 'compexam' => 'coordinators#create_retake', :as => :create_retake

  get 'coordinators/edit_history' => 'coordinators#edit_history', :as => :edit_history
  patch 'coordinators/update_history' => 'coordinators#update_history', :as => :update_history

  get 'coordinators/add_offering' => 'coordinators#add_offering', :as => :add_offering
  post 'offering' => 'coordinators#create_offering'
  get 'coordinators/offering/:id' => 'coordinators#offering_details'
  get 'coordinators/edit_offering' => 'coordinators#edit_offering', :as => :edit_offering
  patch 'coordinators/update_offering' => 'coordinators#update_offering', :as => :update_offering

  get 'coordinators/edit_tfeediscount' => 'coordinators#edit_tfeediscount', :as => :edit_tfeediscount
  patch 'coordinators/update_tfeediscount' => 'coordinators#update_tfeediscount', :as => :update_tfeediscount

  get 'coordinators/edit_roomfee' => 'coordinators#edit_roomfee', :as => :edit_roomfee
  patch 'coordinators/update_roomfee' => 'coordinators#update_roomfee', :as => :update_roomfee
  # programs table
  get 'coordinators/programs'
  get 'coordinators/add_program' => 'coordinators#add_program', :as => :add_program
  post 'programs' => 'coordinators#create_program'
  get 'coordinators/edit_program' => 'coordinators#edit_program', :as => :edit_program
  patch 'coordinators/update_program' => 'coordinators#update_program', :as => :update_program
  get 'coordinators/programs/:id/delete' => 'coordinators#delete_program'
  # specializations
  get 'coordinators/specialization'
  get 'coordinators/add_specialization' => 'coordinators#add_specialization', :as => :add_specialization
  post 'specialization' => 'coordinators#create_specialization'
  get 'coordinators/edit_specialization' => 'coordinators#edit_specialization', :as => :edit_specialization
  patch 'coordinators/update_specialization' => 'coordinators#update_specialization', :as => :update_specialization
  get 'coordinators/specialization/:id/delete' => 'coordinators#delete_specialization'

  get 'coordinators/curriculum'
  get 'coordinators/add_curriculum' => 'coordinators#add_curriculum', :as => :add_curriculum
  post 'curriculum' => 'coordinators#create_curriculum'
  get 'coordinators/edit_curriculum' => 'coordinators#edit_curriculum', :as => :edit_curriculum
  patch 'coordinators/update_curriculum' => 'coordinators#update_curriculum', :as => :update_curriculum
  get 'coordinators/curriculum/:id/delete' => 'coordinators#delete_curriculum'

  get 'coordinators/student'
  get 'coordinators/add_student' => 'coordinators#add_student', :as => :add_student
  post 'student' => 'coordinators#create_student'
  get 'coordinators/edit_student' => 'coordinators#edit_student', :as => :edit_student
  patch 'coordinators/update_student' => 'coordinators#update_student', :as => :update_student
  get 'coordinators/student/:id/delete' => 'coordinators#delete_student'

  get 'coordinators/faculty'
  get 'coordinators/add_faculty' => 'coordinators#add_faculty', :as => :add_faculty
  post 'faculty' => 'coordinators#create_faculty'
  get 'coordinators/edit_faculty' => 'coordinators#edit_faculty', :as => :edit_faculty
  patch 'coordinators/update_faculty' => 'coordinators#update_faculty', :as => :update_faculty
  get 'coordinators/faculty/:id/delete' => 'coordinators#delete_faculty'

  get 'coordinators/subject'
  get 'coordinators/add_subject' => 'coordinators#add_subject', :as => :add_subject
  post 'subject' => 'coordinators#create_subject'
  get 'coordinators/edit_subject' => 'coordinators#edit_subject', :as => :edit_subject
  patch 'coordinators/update_subject' => 'coordinators#update_subject', :as => :update_subject
  get 'coordinators/subject/:id/delete' => 'coordinators#delete_subject'

  get 'coordinators/room'
  get 'coordinators/add_room' => 'coordinators#add_room', :as => :add_room
  post 'room' => 'coordinators#create_room'
  get 'coordinators/edit_room' => 'coordinators#edit_room', :as => :edit_room
  patch 'coordinators/update_room' => 'coordinators#update_room', :as => :update_room
  get 'coordinators/room/:id/delete' => 'coordinators#delete_room'

  get 'coordinators/classtype'
  get 'coordinators/add_classtype' => 'coordinators#add_classtype', :as => :add_classtype
  post 'classtype' => 'coordinators#create_classtype'
  get 'coordinators/edit_classtype' => 'coordinators#edit_classtype', :as => :edit_classtype
  patch 'coordinators/update_classtype' => 'coordinators#update_classtype', :as => :update_classtype
  get 'coordinators/classtype/:id/delete' => 'coordinators#delete_classtype'

  get 'coordinators/fee'
  get 'coordinators/add_fee' => 'coordinators#add_fee', :as => :add_fee
  post 'fee' => 'coordinators#create_fee'
  get 'coordinators/edit_fee' => 'coordinators#edit_fee', :as => :edit_fee
  patch 'coordinators/update_fee' => 'coordinators#update_fee', :as => :update_fee
  get 'coordinators/fee/:id/delete' => 'coordinators#delete_fee'

  get 'coordinators/semester'
  get 'coordinators/add_semester' => 'coordinators#add_semester', :as => :add_semester
  post 'semester' => 'coordinators#create_semester'
  get 'coordinators/edit_semester' => 'coordinators#edit_semester', :as => :edit_semester
  patch 'coordinators/update_semester' =>'coordinators#update_semester', :as => :update_semester
  get 'coordinators/semester/:id/delete' => 'coordinators#delete_semester'

  get 'coordinators/tempsched'
  get 'coordinators/add_tempsched' => 'coordinators#add_tempsched', :as => :add_tempsched
  post 'tempsched' => 'coordinators#create_tempsched'

  get 'coordinators/schoolyear'
  get 'coordinators/add_schoolyear' => 'coordinators#add_schoolyear', :as => :add_schoolyear
  post 'schoolyear' => 'coordinators#create_schoolyear'
  get 'coordinators/edit_schoolyear' => 'coordinators#edit_schoolyear', :as => :edit_schoolyear
  patch 'coordinators/update_schoolyear' => 'coordinators#update_schoolyear', :as => :update_schoolyear

  get 'coordinators/schoolyear'
  get 'coordinators/schoolyear/:id/delete' => 'coordinators#delete_schoolyear'


  get 'coordinators/compexam/student_exam/exam_details/:id' => 'coordinators#exam_details'
  get 'coordinators/compexam'
  get 'coordinators/compexam/student_exams/:id' => 'coordinators#student_exams'
  get 'coordinators/compexam/apply/:id' => 'coordinators#apply', :as => :n_application
  post 'compexamapps' => 'coordinators#create_application', :as => :new_application

  get 'coordinators/compexamapps'
  get 'coordinators/classlist'
  
  get 'coordinators/edit_compexamsubj' => 'coordinators#edit_compexamsubj', :as => :edit_compexamsubj
  patch 'coordinators/update_compexamsubj' => 'coordinators#update_compexamsubj', :as => :update_compexamsubj

  get 'coordinators/enlist'
  get 'coordinators/:id' => 'coordinators#enlist_student', :as => :enlistment
  get 'coordinators/:sid/enlist_subject/:id' => 'coordinators#enlist_subject', :as => :cenlist_subject
  get 'coordinators/:sid/drop/:id' => 'coordinators#drop_subject'

  get 'students/dashboard'
  get 'students/compexam'
  get 'students/compexam/apply' => 'students#apply', :as => :s_application

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/_edit_contpan.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Edit Settings</h2>
		</div>
		<%= form_for(@contpan, :url => update_contpan_path(:id => params[:id]), :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :site, "Site Title", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :site_name, class: "form-control", placeholder: "Up to 35 characters only" %>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-2">
					<%= f.label :sy, "School Year", class: "col-sm-2 control-label" %>
					</div>
					<% @sy = Schoolyear.all %>
					<div class="col-sm-3">
							<%= f.select(:schoolyear_id, @sy.collect {|subject| [@st = subject.startyr.to_s + " - " + subject.endyear.to_s, subject.id ]}, {class: "form-control"}) %>
					</div>

					<div class="col-sm-2">
					<%= f.label :sem, "Semester", class: "col-sm-2 control-label" %>
					</div>
					<% @sem = Semester.all %>
					<div class="col-sm-3">
							<%= f.select(:semester_id, @sem.collect {|s| [@st = s.sem_name, s.id ]}, {class: "form-control"}) %>
					</div>

				</div>
				<div class="form-group">
					<%= f.label :college, "College", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :college, class: "form-control" %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :dept, "Department", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :department, class: "form-control" %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :name, "Coordinator's Full Name", class: "col-sm-2 control-label" %>
				<div class="col-sm-10">
					<%= f.text_field :full_name, class: "form-control" %>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">

					<button type="button" class="btn btn-default btn-primary btn-block" data-toggle="modal" data-target="#promptSubmit">
						Update
					</button>

					<div class="modal fade" id="promptSubmit" role="dialog">
					    <div class="modal-dialog">
					      <div class="modal-content">
					        <div class="modal-body">
										<div class="row">
											<div class="col-md-8">
												<p>Are you sure you want to update this settings?</p>
											</div>
											<div class="col-md-4">
												<button type="button" class="btn btn-default btn-sm pull-right" data-dismiss="modal">NO</button>
												<center><%= f.submit "YES", class: "btn btn-default btn-success btn-sm", :id => "submitform" %></center>
											</div>
										</div>
					        </div>
					      </div>
					    </div>
					</div>

				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/coordinators/_edit_program.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Edit Teacher</h2>
		</div>
		<%= form_for(@program, :url => update_program_path(:id => params[:id]), :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :program_title, "Program", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :program_title, class: "form-control" %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">

					<button type="button" class="btn btn-default btn-primary btn-block" data-toggle="modal" data-target="#promptSubmit">
						Update
					</button>

					<div class="modal fade" id="promptSubmit" role="dialog">
					    <div class="modal-dialog">
					      <div class="modal-content">
					        <div class="modal-body">
										<div class="row">
											<div class="col-md-8">
												<p>Are you sure you want to update this program?</p>
											</div>
											<div class="col-md-4">
												<button type="button" class="btn btn-default btn-sm pull-right" data-dismiss="modal">NO</button>
												<center><%= f.submit "YES", class: "btn btn-default btn-success btn-sm", :id => "submitform" %></center>
											</div>
										</div>
					        </div>
					      </div>
					    </div>
					</div>

				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/coordinators/_edit_schoolyear.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Edit School Year</h2>
		</div>
		<%= form_for(@schoolyear, :url => update_schoolyear_path(:id => params[:id]), :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :startyr, "Start Year", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :startyr, class: "form-control" %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :endyear, "End Year", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :endyear, class: "form-control" %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">

					<button type="button" class="btn btn-default btn-primary btn-block" data-toggle="modal" data-target="#promptSubmit">
						Update
					</button>

					<div class="modal fade" id="promptSubmit" role="dialog">
					    <div class="modal-dialog">
					      <div class="modal-content">
					        <div class="modal-body">
										<div class="row">
											<div class="col-md-8">
												<p>Are you sure you want to update this school year?</p>
											</div>
											<div class="col-md-4">
												<button type="button" class="btn btn-default btn-sm pull-right" data-dismiss="modal">NO</button>
												<center><%= f.submit "YES", class: "btn btn-default btn-success btn-sm", :id => "submitform" %></center>
											</div>
										</div>
					        </div>
					      </div>
					    </div>
					</div>

				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/coordinators/_edit_tempval.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Update Exam Settings</h2>
		</div>
		<%= form_for(@tempval, :url => update_tempval_path(:id => params[:id]), :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :subjtot, "Subjects to Take:", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :subjtotake, class: "form-control" %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :subjtot, "Subjects to Pass:", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :default_subjtopass, class: "form-control" %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">

					<button type="button" class="btn btn-default btn-primary btn-block" data-toggle="modal" data-target="#promptSubmit">
						Update
					</button>

					<div class="modal fade" id="promptSubmit" role="dialog">
					    <div class="modal-dialog">
					      <div class="modal-content">
					        <div class="modal-body">
										<div class="row">
											<div class="col-md-8">
												<p>Are you sure you want to update the exam settings?</p>
											</div>
											<div class="col-md-4">
												<button type="button" class="btn btn-default btn-sm pull-right" data-dismiss="modal">NO</button>
												<center><%= f.submit "YES", class: "btn btn-default btn-success btn-sm", :id => "submitform" %></center>
											</div>
										</div>
					        </div>
					      </div>
					    </div>
					</div>

				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/coordinators/edit_program.js.erb
$(document).ready( function() {
	$("#edit_program").html("<%= escape_javascript(render 'coordinators/edit_program') %>");
	$('#edit_program').modal('show');
});

$("#submitform").click( function() {
  $( '#edit_program' ).modal( 'hide' );
});

$('#edit_program').on('hidden.bs.modal', function () {
	setTimeout('history.go(0);');
})

app/views/coordinators/semester.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-th"></span>Semester
                </li>
            </ol>

            <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-4">
                      Semester Info
                  </div>
                  <div class="col-xs-4">
                  </div>
                  <div class="col-xs-4">
                    <%= link_to add_semester_path, {:remote => true, 'data-toggle' => "modal", 'data-target' => '#add_semester', method: 'get', :class => 'btn btn-sm btn-success pull-right'} do %>
                      <span class="glyphicon glyphicon-plus"></span>
                    <% end %>
                  </div>
                </div>
            </div>

            <div class="panel-body">

              <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name %>" role="alert">
                  <b><%= msg %></b>
                  <ul>
                    <li> Input must have <b>atleast 3 characters</b>.</li>
                    <li> Input only accepts <b>letters and numbers</b>.</li>
                    <li> Semester may already <b>exist</b>.</li>
                  </ul>
                </div>
              <% end %>

            <table id="datatabs" class="table display table-bordered">
              <thead>
                <tr>
                  <th>Semester</th>
                  <th style="width: 11%"></th>
                </tr>
              </thead>
              <tbody>
                <% @semester.each do |s| %>
                <tr>
                    <td><%= s.sem_name %></td>
                    <td>
                        <div class="row">
                          <div class="col-sm-6">
                          <%= link_to edit_semester_path(:id => s.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#edit_semester', :class => 'btn btn-warning btn-sm'} do %>
                          <span class="glyphicon glyphicon-pencil"></span>
                          <% end %>
                          </div>
                          <div class="col-sm-6">
                            <a href="/coordinators/semester/<%= s.id%>/delete" class="btn btn-danger btn-sm" data-confirm="Are you sure?">
                              <span class="glyphicon glyphicon-remove"></span>
                            </a>
                          </div>
                        </div>
                    </td>
                </tr>
                <% end %>
              </tbody>
            </table>
            </div>
        </div>

        <!-- /.col-lg-12 -->
    </div>
</div>
<div id="add_semester" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<div id="edit_semester" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/coordinators/settings.html.erb
<div id="page-wrapper">
    <div class="row">
      <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="fa fa-cog"></span> Settings
                </li>
            </ol>
            <% @contpan.each do |c| %>
            <div class="row">
                <div class="col-md-9">
                    <div class="panel-heading custompanel">
                      <h4 class="semibold nm">SYSTEM SETTINGS</h4>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-sm-2">
                              Site Title
                            </div>
                            <div class="col-sm-10">
                                <%= c.site_name %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2">
                              School Year
                            </div>
                            <div class="col-sm-10">
                              <% @sy = Schoolyear.find(c.schoolyear_id) %>
                              <%= @sy.startyr %>-<%= @sy.endyear %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2">
                              Semester
                            </div>
                            <div class="col-sm-10">
                              <%= Semester.find(c.semester_id).sem_name %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2">
                              College
                            </div>
                            <div class="col-sm-10">
                              <%= c.college %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2">
                              Department
                            </div>
                            <div class="col-sm-10">
                              <%= c.department %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2">
                              Coordinator Name
                            </div>
                            <div class="col-sm-10">
                              <%= c.full_name %>
                            </div>
                        </div>
                        <%= link_to edit_contpan_path(:id => c.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#edit_contpan'} do %>
                                <button type="button" class="btn btn-primary">Change Settings</button>
                        <% end %>
                    </div>
                  </div>
                </div>
                <% end %>
                <% @tempval.each do |t| %>
                <div class="row">
                  <div class="col-md-9">
                    <div class="panel-heading custompanel">
                      <h4 class="semibold nm">COMPREHENSIVE EXAM SETTINGS</h4>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-sm-4">
                              Required Subjects to take
                            </div>
                            <div class="col-sm-8">
                                <%= t.subjtotake %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                              Required subjects to pass
                            </div>
                            <div class="col-sm-8">
                                <%= t.default_subjtopass %>
                            </div>
                        </div>
                        <%= link_to edit_tempval_path(:id => t.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#edit_tempval'} do %>
                                <button type="button" class="btn btn-primary">Change Settings</button>
                        <% end %>
                    </div>
                  </div>
                </div>
                <% end %>
            </div>
        </div>
  </div>


<div id="edit_contpan" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<div id="edit_tempval" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/coordinators/specialization.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-th"></span>Specializations
                </li>
            </ol>
            <h4>Field of Specializations</h4>

            <div class="panel-body">

              <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name %>" role="alert">
                  <b><%= msg %></b>
                  <ul>
                    <li> Spec Name must be <b>atleast 5 characters</b>.</li>
                    <li> Spec Name only accepts <b>letters, numbers and selected special characters (' - ' and ' , ')</b>.</li>
                    <li> Choose a <b>Program Track</b>.</li>
                    <li> Spec Name <b>may already be taken</b>.</li>
                  </ul>
                </div>
              <% end %>

              <div class="panel-heading">
                  <div class="row">
                    <div class="col-xs-4">
                        Specializations
                    </div>
                    <div class="col-xs-4"></div>
                    <div class="col-xs-4">
                      <%= link_to add_specialization_path, {:remote => true, 'data-toggle' => "modal", 'data-target' => '#add_program', method: 'get', :class => 'btn btn-sm btn-success pull-right'} do %>
                        <span class="glyphicon glyphicon-plus"></span>
                      <% end %>
                    </div>
                    <div class="col-xs-4">
                    </div>
                  </div>
              </div>
            <table id="datatabs" class="table display table-bordered">
              <thead>
                <tr>
                  <th>Field of Specializations</th>
                  <th style="text-align: center">Program Track</th>
                  <th style="width: 10%"></th>
                </tr>
              </thead>
              <tbody>
                <% @specialization.each do |s| %>
                <tr>
                    <td><%= s.spec_name %></td>
                    <% @id = s.program_id %>
                    <% @tempCol = Program.where(id: @id) %>
                    <% @tempCol.each do |te| %>
                        <% @container = te.program_title %>
                    <% end %>
                    <td><%= @container %></td>
                    <td>
                        <div class="row">
                          <div class="col-sm-4">
                            <%= link_to edit_specialization_path(:id =>s.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => "#edit_specialization", :class => "btn btn-sm btn-warning"} do %>
                              <span class="glyphicon glyphicon-pencil"></span>
                            <% end %>
                          </div>
                          <div class="col-sm-4">
                              <a class="btn btn-sm btn-danger" href="/coordinators/specialization/<%= s.id %>/delete" data-confirm="Are you sure?">
                                  <span class="glyphicon glyphicon-remove"></span>
                              </a>
                          </div>
                        </div>
                    </td>
                </tr>
                <% end %>
              </tbody>
            </table>
            </div>
        </div>

        <!-- /.col-lg-12 -->
    </div>
</div>
<div id="add_specialization" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<div id="edit_specialization" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>