config/routes.rb
Rails.application.routes.draw do

  get 'coordinators/settings'
  get 'coordinators/help'
  get 'students/help'

  get 'users/home'

  get 'sessions/new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get 'coordinators/edit_password' => 'coordinators#edit_password', :as => :cedit_password
  patch 'coordinators/update_password' => 'coordinators#update_password', :as => :update_password

  get 'teachers/edit_password' => 'teachers#edit_password'
  patch 'teachers/update_password' => 'teachers#update_password', :as => :update_passwordt

  get 'students/edit_password' => 'students#edit_password'
  patch 'students/update_password' => 'students#update_password', :as => :update_passwords

  get 'users/edit_password' => 'users#edit_password'
  patch 'users/update_password' => 'users#update_password', :as => :update_passwordu
  get 'teachers/profile' => 'teachers#profile'
  get 'students/profile' => 'students#profile'

  get 'coordinators/edit_compexam' => 'coordinators#edit_compexam', :as => :edit_compexam
  patch 'coordinators/update_compexam' => 'coordinators#update_compexam', :as => :update_compexam

  get 'coordinators/add_appearance' => 'coordinators#add_appearance', :as => :add_appearance
  post 'appearance' => 'coordinators#create_appearance'
  get 'coordinators/edit_appearance' => 'coordinators#edit_appearance', :as => :edit_appearance
  patch 'coordinators/update_appearance' => 'coordinators#update_appearance', :as => :update_appearance

  get 'coordinators/discount'
  get 'coordinators/add_discount' => 'coordinators#add_discount', :as => :add_discount
  post 'discount' => 'coordinators#create_discount'
  get 'coordinators/edit_discount' => 'coordinators#edit_discount', :as => :edit_discount
  patch 'coordinators/update_discount' => 'coordinators#update_discount', :as => :update_discount
  get 'coordinators/discount/:id/delete' => 'coordinators#delete_discount'

  get 'coordinators/dashboard'
  get 'coordinators/edit_contpan' => 'coordinators#edit_contpan', :as => :edit_contpan
  patch 'coordinators/edit_contpan' => 'coordinators#update_contpan',:as => :update_contpan
  get 'coordinators/edit_tempval' => 'coordinators#edit_tempval', :as => :edit_tempval
  patch 'coordinators/update_tempval' => 'coordinators#update_tempval', :as => :update_tempval

  get 'coordinators/studentsubjects/:id' => 'coordinators#studentsubjects'
  get 'coordinators/offering'
  get 'coordinators/compexam'

  get 'coordinators/offering/:id/delete' => 'coordinators#delete_offering'

  get 'coordinators/enrollmentdata'
  get 'coordinators/tuition'
  get 'coordinators/roomandfee'
  get 'coordinators/facultyloading'
  #get 'coordinators/:sid/retake/:id' => 'coordinators#retake'

  get 'coordinators/add_retake' => 'coordinators#add_retake', :as => :add_retake
  post 'compexam' => 'coordinators#create_retake', :as => :create_retake

  get 'coordinators/edit_history' => 'coordinators#edit_history', :as => :edit_history
  patch 'coordinators/update_history' => 'coordinators#update_history', :as => :update_history

  get 'coordinators/add_offering' => 'coordinators#add_offering', :as => :add_offering
  post 'offering' => 'coordinators#create_offering'
  get 'coordinators/offering/:id' => 'coordinators#offering_details'
  get 'coordinators/edit_offering' => 'coordinators#edit_offering', :as => :edit_offering
  patch 'coordinators/update_offering' => 'coordinators#update_offering', :as => :update_offering

  get 'coordinators/edit_tfeediscount' => 'coordinators#edit_tfeediscount', :as => :edit_tfeediscount
  patch 'coordinators/update_tfeediscount' => 'coordinators#update_tfeediscount', :as => :update_tfeediscount

  get 'coordinators/edit_roomfee' => 'coordinators#edit_roomfee', :as => :edit_roomfee
  patch 'coordinators/update_roomfee' => 'coordinators#update_roomfee', :as => :update_roomfee
  # programs table
  get 'coordinators/programs'
  get 'coordinators/add_program' => 'coordinators#add_program', :as => :add_program
  post 'programs' => 'coordinators#create_program'
  get 'coordinators/edit_program' => 'coordinators#edit_program', :as => :edit_program
  patch 'coordinators/update_program' => 'coordinators#update_program', :as => :update_program
  get 'coordinators/programs/:id/delete' => 'coordinators#delete_program'
  # specializations
  get 'coordinators/specialization'
  get 'coordinators/add_specialization' => 'coordinators#add_specialization', :as => :add_specialization
  post 'specialization' => 'coordinators#create_specialization'
  get 'coordinators/edit_specialization' => 'coordinators#edit_specialization', :as => :edit_specialization
  patch 'coordinators/update_specialization' => 'coordinators#update_specialization', :as => :update_specialization
  get 'coordinators/specialization/:id/delete' => 'coordinators#delete_specialization'

  get 'coordinators/curriculum'
  get 'coordinators/add_curriculum' => 'coordinators#add_curriculum', :as => :add_curriculum
  post 'curriculum' => 'coordinators#create_curriculum'
  get 'coordinators/edit_curriculum' => 'coordinators#edit_curriculum', :as => :edit_curriculum
  patch 'coordinators/update_curriculum' => 'coordinators#update_curriculum', :as => :update_curriculum
  get 'coordinators/curriculum/:id/delete' => 'coordinators#delete_curriculum'

  get 'coordinators/student'
  get 'coordinators/add_student' => 'coordinators#add_student', :as => :add_student
  post 'student' => 'coordinators#create_student'
  get 'coordinators/edit_student' => 'coordinators#edit_student', :as => :edit_student
  patch 'coordinators/update_student' => 'coordinators#update_student', :as => :update_student
  get 'coordinators/student/:id/delete' => 'coordinators#delete_student'

  get 'coordinators/faculty'
  get 'coordinators/add_faculty' => 'coordinators#add_faculty', :as => :add_faculty
  post 'faculty' => 'coordinators#create_faculty'
  get 'coordinators/edit_faculty' => 'coordinators#edit_faculty', :as => :edit_faculty
  patch 'coordinators/update_faculty' => 'coordinators#update_faculty', :as => :update_faculty
  get 'coordinators/faculty/:id/delete' => 'coordinators#delete_faculty'

  get 'coordinators/subject'
  get 'coordinators/add_subject' => 'coordinators#add_subject', :as => :add_subject
  post 'subject' => 'coordinators#create_subject'
  get 'coordinators/edit_subject' => 'coordinators#edit_subject', :as => :edit_subject
  patch 'coordinators/update_subject' => 'coordinators#update_subject', :as => :update_subject
  get 'coordinators/subject/:id/delete' => 'coordinators#delete_subject'

  get 'coordinators/room'
  get 'coordinators/add_room' => 'coordinators#add_room', :as => :add_room
  post 'room' => 'coordinators#create_room'
  get 'coordinators/edit_room' => 'coordinators#edit_room', :as => :edit_room
  patch 'coordinators/update_room' => 'coordinators#update_room', :as => :update_room
  get 'coordinators/room/:id/delete' => 'coordinators#delete_room'

  get 'coordinators/classtype'
  get 'coordinators/add_classtype' => 'coordinators#add_classtype', :as => :add_classtype
  post 'classtype' => 'coordinators#create_classtype'
  get 'coordinators/edit_classtype' => 'coordinators#edit_classtype', :as => :edit_classtype
  patch 'coordinators/update_classtype' => 'coordinators#update_classtype', :as => :update_classtype
  get 'coordinators/classtype/:id/delete' => 'coordinators#delete_classtype'

  get 'coordinators/fee'
  get 'coordinators/add_fee' => 'coordinators#add_fee', :as => :add_fee
  post 'fee' => 'coordinators#create_fee'
  get 'coordinators/edit_fee' => 'coordinators#edit_fee', :as => :edit_fee
  patch 'coordinators/update_fee' => 'coordinators#update_fee', :as => :update_fee
  get 'coordinators/fee/:id/delete' => 'coordinators#delete_fee'

  get 'coordinators/semester'
  get 'coordinators/add_semester' => 'coordinators#add_semester', :as => :add_semester
  post 'semester' => 'coordinators#create_semester'
  get 'coordinators/edit_semester' => 'coordinators#edit_semester', :as => :edit_semester
  patch 'coordinators/update_semester' =>'coordinators#update_semester', :as => :update_semester
  get 'coordinators/semester/:id/delete' => 'coordinators#delete_semester'

  get 'coordinators/tempsched'
  get 'coordinators/add_tempsched' => 'coordinators#add_tempsched', :as => :add_tempsched
  post 'tempsched' => 'coordinators#create_tempsched'

  get 'coordinators/schoolyear'
  get 'coordinators/add_schoolyear' => 'coordinators#add_schoolyear', :as => :add_schoolyear
  post 'schoolyear' => 'coordinators#create_schoolyear'
  get 'coordinators/edit_schoolyear' => 'coordinators#edit_schoolyear', :as => :edit_schoolyear
  patch 'coordinators/update_schoolyear' => 'coordinators#update_schoolyear', :as => :update_schoolyear

  get 'coordinators/schoolyear'
  get 'coordinators/schoolyear/:id/delete' => 'coordinators#delete_schoolyear'


  get 'coordinators/compexam/student_exam/exam_details/:id' => 'coordinators#exam_details'
  get 'coordinators/compexam'
  get 'coordinators/compexam/student_exams/:id' => 'coordinators#student_exams'
  get 'coordinators/compexam/apply/:id' => 'coordinators#apply', :as => :n_application
  post 'compexamapps' => 'coordinators#create_application', :as => :new_application

  get 'coordinators/compexamapps'
  get 'coordinators/classlist'
  
  get 'coordinators/edit_compexamsubj' => 'coordinators#edit_compexamsubj', :as => :edit_compexamsubj
  patch 'coordinators/update_compexamsubj' => 'coordinators#update_compexamsubj', :as => :update_compexamsubj

  get 'coordinators/enlist'
  get 'coordinators/:id' => 'coordinators#enlist_student', :as => :enlistment
  get 'coordinators/:sid/enlist_subject/:id' => 'coordinators#enlist_subject', :as => :cenlist_subject
  get 'coordinators/:sid/drop/:id' => 'coordinators#drop_subject'

  get 'students/dashboard'
  get 'students/compexam'
  get 'students/compexam/apply' => 'students#apply', :as => :s_application

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	#  Line 7-8
	#  Checks the password if it is correct

	validates :password, presence: true, length: {minimum: 5}, :if => :password
	validates_confirmation_of :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :require_login, :set_cache_buster	
  def home
  	@user = User.where.not(id: current_user.id)
  end

  def edit_user
  	@user = User.find(params[:id])
  	@role = Array.new
  	@role << "Coordinator"
  	@role << "Teacher"
  	respond_to do |format|
  		format.html
  		format.js
  	end
  end

  def update_user
  	@user = User.find(params[:id])
  	@user.update_attributes(:username => params[:user][:username])
  	@user.update_attributes(:role => params[:user][:role])
  	@user.save!  
  	redirect_to '/users/home'
  end

  def edit_password
    @user = User.find(current_user.id)
  end

  def update_password
    @user = User.find(current_user.id)
    user = User.find(current_user.id).try(:authenticate, params[:current_password])
    if user && @user.update_attributes(user_params)
      @user.save
      redirect_to '/users/home'
      gflash success: "Password updated"
    else
      redirect_to 'users/edit_password'
      flash.now[:error] = "Incorrect current password"
    end
  end
  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  	def require_login
    	unless logged_in?
	      	flash[:error] = "Hello"
	      	redirect_to login_url
	    	end
 	 end

  	def set_cache_buster
    	response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    	response.headers["Pragma"] = "no-cache"
    	response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  	end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_user.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Edit User</h2>
		</div>
		<%= form_for(@user, :url => update_user_path(:id => params[:id]), :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :fee_name, "Username", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :username, class: "form-control" %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :fee_name, "Role", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<% @count = 0 %>
						<%= f.select :role, @role.collect { |program| [program, @count = @count + 1] }, :prompt => 'Select One' %>
					</div>
				</div>		
			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">

					<button type="button" class="btn btn-default btn-primary btn-block" data-toggle="modal" data-target="#promptSubmit">
						Update
					</button>

					<div class="modal fade" id="promptSubmit" role="dialog">
					    <div class="modal-dialog">
					      <div class="modal-content">
					        <div class="modal-body">
										<div class="row">
											<div class="col-md-8">
												<p>Are you sure you want to update this user?</p>
											</div>
											<div class="col-md-4">
												<button type="button" class="btn btn-default btn-sm pull-right" data-dismiss="modal">NO</button>
												<center><%= f.submit "YES", class: "btn btn-default btn-success btn-sm", :id => "submitform" %></center>
											</div>
										</div>
					        </div>
					      </div>
					    </div>
					</div>

				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/edit_password.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Dashboard
                </li>
                <li class = "">
                    <span class="glyphicon glyphicon-th"></span>Change Password
                </li>
            </ol>
            <div class="row">
                <div class="col-md-9">
                    <div class="panel-heading custompanel">
                      <h4 class="semibold nm">CHANGE PASSWORD</h4>
                    </div>
                    <div class="panel-body">
                        <%= form_for(@user, :url => update_passwordu_path) do |f| %>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "Old Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= password_field_tag :current_password, params[:current_password] %>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "New Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= f.password_field :password %>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "Confirm Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= f.password_field :password_confirmation %>
                              </div>
                          </div>
                            <div class="col-sm-6">
                              <%= f.submit "Update Password", class: "btn btn-info btm-sm" %>
                            </div>
                        <% end %>                        
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

app/views/users/edit_user.js.erb
$(document).ready( function() {
	$("#edit_user").html("<%= escape_javascript(render 'users/edit_user') %>");
	$('#edit_user').modal('show');
});

$("#submitform").click( function() {
  $( '#edit_user' ).modal( 'hide' );
});

$('#edit_user').on('hidden.bs.modal', function () {
	setTimeout('history.go(0);');
})

app/views/users/home.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Manage Users
                </li>
            </ol>
            <div class="panel-heading">
                  <div class="row">
                    <div class="col-xs-4">
                        <b>MANAGE USERS</b>
                    </div>
                  </div>
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 7%"></th>
                            <th>Username</th>
                            <th style="text-align: center">User</th>
                            <th style="text-align: center">Role</th>
                            <th style="width: 7%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @count = 0 %>
                        <% @user.each do |u| %>
                            <% @len = u.username.length %>
                            <% @id = u.username.slice(1..@len).to_s %>
                            <% @f = Faculty.find_by(f_id: @id) %>
                            <tr>
                                <td style="text-align: center"><%= @count = @count + 1 %></td>
                                <td><%= u.username %></td>
                                <td><%= @f.f_lname %></td>
                                <td>
                                    <% if u.role == 1 %>
                                        <%= "Admin" %>
                                    <% elsif u.role == 3 %>
                                        <%= "Teacher" %>
                                    <% else %>
                                        <%= "Coordinator" %>
                                    <% end %>
                                </td>
                                <td>
                                  <%= link_to edit_user_path(:id => u.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#edit_user', :class => "btn btn-sm btn-warning"} do %>
                                        <span class="glyphicon glyphicon-pencil"></span>
                                  <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div> 
        </div>
    </div>
</div>
<div id="edit_user" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>