config/routes.rb
Rails.application.routes.draw do

  get 'coordinators/settings'
  get 'coordinators/help'
  get 'students/help'

  get 'users/home'

  get 'sessions/new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get 'coordinators/edit_password' => 'coordinators#edit_password', :as => :cedit_password
  patch 'coordinators/update_password' => 'coordinators#update_password', :as => :update_password

  get 'teachers/edit_password' => 'teachers#edit_password'
  patch 'teachers/update_password' => 'teachers#update_password', :as => :update_passwordt

  get 'students/edit_password' => 'students#edit_password'
  patch 'students/update_password' => 'students#update_password', :as => :update_passwords

  get 'users/edit_password' => 'users#edit_password'
  patch 'users/update_password' => 'users#update_password', :as => :update_passwordu
  get 'teachers/profile' => 'teachers#profile'
  get 'students/profile' => 'students#profile'

  get 'coordinators/edit_compexam' => 'coordinators#edit_compexam', :as => :edit_compexam
  patch 'coordinators/update_compexam' => 'coordinators#update_compexam', :as => :update_compexam

  get 'coordinators/add_appearance' => 'coordinators#add_appearance', :as => :add_appearance
  post 'appearance' => 'coordinators#create_appearance'
  get 'coordinators/edit_appearance' => 'coordinators#edit_appearance', :as => :edit_appearance
  patch 'coordinators/update_appearance' => 'coordinators#update_appearance', :as => :update_appearance

  get 'coordinators/discount'
  get 'coordinators/add_discount' => 'coordinators#add_discount', :as => :add_discount
  post 'discount' => 'coordinators#create_discount'
  get 'coordinators/edit_discount' => 'coordinators#edit_discount', :as => :edit_discount
  patch 'coordinators/update_discount' => 'coordinators#update_discount', :as => :update_discount
  get 'coordinators/discount/:id/delete' => 'coordinators#delete_discount'

  get 'coordinators/dashboard'
  get 'coordinators/edit_contpan' => 'coordinators#edit_contpan', :as => :edit_contpan
  patch 'coordinators/edit_contpan' => 'coordinators#update_contpan',:as => :update_contpan
  get 'coordinators/edit_tempval' => 'coordinators#edit_tempval', :as => :edit_tempval
  patch 'coordinators/update_tempval' => 'coordinators#update_tempval', :as => :update_tempval

  get 'coordinators/studentsubjects/:id' => 'coordinators#studentsubjects'
  get 'coordinators/offering'
  get 'coordinators/compexam'

  get 'coordinators/offering/:id/delete' => 'coordinators#delete_offering'

  get 'coordinators/enrollmentdata'
  get 'coordinators/tuition'
  get 'coordinators/roomandfee'
  get 'coordinators/facultyloading'
  #get 'coordinators/:sid/retake/:id' => 'coordinators#retake'

  get 'coordinators/add_retake' => 'coordinators#add_retake', :as => :add_retake
  post 'compexam' => 'coordinators#create_retake', :as => :create_retake

  get 'coordinators/edit_history' => 'coordinators#edit_history', :as => :edit_history
  patch 'coordinators/update_history' => 'coordinators#update_history', :as => :update_history

  get 'coordinators/add_offering' => 'coordinators#add_offering', :as => :add_offering
  post 'offering' => 'coordinators#create_offering'
  get 'coordinators/offering/:id' => 'coordinators#offering_details'
  get 'coordinators/edit_offering' => 'coordinators#edit_offering', :as => :edit_offering
  patch 'coordinators/update_offering' => 'coordinators#update_offering', :as => :update_offering

  get 'coordinators/edit_tfeediscount' => 'coordinators#edit_tfeediscount', :as => :edit_tfeediscount
  patch 'coordinators/update_tfeediscount' => 'coordinators#update_tfeediscount', :as => :update_tfeediscount

  get 'coordinators/edit_roomfee' => 'coordinators#edit_roomfee', :as => :edit_roomfee
  patch 'coordinators/update_roomfee' => 'coordinators#update_roomfee', :as => :update_roomfee
  # programs table
  get 'coordinators/programs'
  get 'coordinators/add_program' => 'coordinators#add_program', :as => :add_program
  post 'programs' => 'coordinators#create_program'
  get 'coordinators/edit_program' => 'coordinators#edit_program', :as => :edit_program
  patch 'coordinators/update_program' => 'coordinators#update_program', :as => :update_program
  get 'coordinators/programs/:id/delete' => 'coordinators#delete_program'
  # specializations
  get 'coordinators/specialization'
  get 'coordinators/add_specialization' => 'coordinators#add_specialization', :as => :add_specialization
  post 'specialization' => 'coordinators#create_specialization'
  get 'coordinators/edit_specialization' => 'coordinators#edit_specialization', :as => :edit_specialization
  patch 'coordinators/update_specialization' => 'coordinators#update_specialization', :as => :update_specialization
  get 'coordinators/specialization/:id/delete' => 'coordinators#delete_specialization'

  get 'coordinators/curriculum'
  get 'coordinators/add_curriculum' => 'coordinators#add_curriculum', :as => :add_curriculum
  post 'curriculum' => 'coordinators#create_curriculum'
  get 'coordinators/edit_curriculum' => 'coordinators#edit_curriculum', :as => :edit_curriculum
  patch 'coordinators/update_curriculum' => 'coordinators#update_curriculum', :as => :update_curriculum
  get 'coordinators/curriculum/:id/delete' => 'coordinators#delete_curriculum'

  get 'coordinators/student'
  get 'coordinators/add_student' => 'coordinators#add_student', :as => :add_student
  post 'student' => 'coordinators#create_student'
  get 'coordinators/edit_student' => 'coordinators#edit_student', :as => :edit_student
  patch 'coordinators/update_student' => 'coordinators#update_student', :as => :update_student
  get 'coordinators/student/:id/delete' => 'coordinators#delete_student'

  get 'coordinators/faculty'
  get 'coordinators/add_faculty' => 'coordinators#add_faculty', :as => :add_faculty
  post 'faculty' => 'coordinators#create_faculty'
  get 'coordinators/edit_faculty' => 'coordinators#edit_faculty', :as => :edit_faculty
  patch 'coordinators/update_faculty' => 'coordinators#update_faculty', :as => :update_faculty
  get 'coordinators/faculty/:id/delete' => 'coordinators#delete_faculty'

  get 'coordinators/subject'
  get 'coordinators/add_subject' => 'coordinators#add_subject', :as => :add_subject
  post 'subject' => 'coordinators#create_subject'
  get 'coordinators/edit_subject' => 'coordinators#edit_subject', :as => :edit_subject
  patch 'coordinators/update_subject' => 'coordinators#update_subject', :as => :update_subject
  get 'coordinators/subject/:id/delete' => 'coordinators#delete_subject'

  get 'coordinators/room'
  get 'coordinators/add_room' => 'coordinators#add_room', :as => :add_room
  post 'room' => 'coordinators#create_room'
  get 'coordinators/edit_room' => 'coordinators#edit_room', :as => :edit_room
  patch 'coordinators/update_room' => 'coordinators#update_room', :as => :update_room
  get 'coordinators/room/:id/delete' => 'coordinators#delete_room'

  get 'coordinators/classtype'
  get 'coordinators/add_classtype' => 'coordinators#add_classtype', :as => :add_classtype
  post 'classtype' => 'coordinators#create_classtype'
  get 'coordinators/edit_classtype' => 'coordinators#edit_classtype', :as => :edit_classtype
  patch 'coordinators/update_classtype' => 'coordinators#update_classtype', :as => :update_classtype
  get 'coordinators/classtype/:id/delete' => 'coordinators#delete_classtype'

  get 'coordinators/fee'
  get 'coordinators/add_fee' => 'coordinators#add_fee', :as => :add_fee
  post 'fee' => 'coordinators#create_fee'
  get 'coordinators/edit_fee' => 'coordinators#edit_fee', :as => :edit_fee
  patch 'coordinators/update_fee' => 'coordinators#update_fee', :as => :update_fee
  get 'coordinators/fee/:id/delete' => 'coordinators#delete_fee'

  get 'coordinators/semester'
  get 'coordinators/add_semester' => 'coordinators#add_semester', :as => :add_semester
  post 'semester' => 'coordinators#create_semester'
  get 'coordinators/edit_semester' => 'coordinators#edit_semester', :as => :edit_semester
  patch 'coordinators/update_semester' =>'coordinators#update_semester', :as => :update_semester
  get 'coordinators/semester/:id/delete' => 'coordinators#delete_semester'

  get 'coordinators/tempsched'
  get 'coordinators/add_tempsched' => 'coordinators#add_tempsched', :as => :add_tempsched
  post 'tempsched' => 'coordinators#create_tempsched'

  get 'coordinators/schoolyear'
  get 'coordinators/add_schoolyear' => 'coordinators#add_schoolyear', :as => :add_schoolyear
  post 'schoolyear' => 'coordinators#create_schoolyear'
  get 'coordinators/edit_schoolyear' => 'coordinators#edit_schoolyear', :as => :edit_schoolyear
  patch 'coordinators/update_schoolyear' => 'coordinators#update_schoolyear', :as => :update_schoolyear

  get 'coordinators/schoolyear'
  get 'coordinators/schoolyear/:id/delete' => 'coordinators#delete_schoolyear'


  get 'coordinators/compexam/student_exam/exam_details/:id' => 'coordinators#exam_details'
  get 'coordinators/compexam'
  get 'coordinators/compexam/student_exams/:id' => 'coordinators#student_exams'
  get 'coordinators/compexam/apply/:id' => 'coordinators#apply', :as => :n_application
  post 'compexamapps' => 'coordinators#create_application', :as => :new_application

  get 'coordinators/compexamapps'
  get 'coordinators/classlist'
  
  get 'coordinators/edit_compexamsubj' => 'coordinators#edit_compexamsubj', :as => :edit_compexamsubj
  patch 'coordinators/update_compexamsubj' => 'coordinators#update_compexamsubj', :as => :update_compexamsubj

  get 'coordinators/enlist'
  get 'coordinators/:id' => 'coordinators#enlist_student', :as => :enlistment
  get 'coordinators/:sid/enlist_subject/:id' => 'coordinators#enlist_subject', :as => :cenlist_subject
  get 'coordinators/:sid/drop/:id' => 'coordinators#drop_subject'

  get 'students/dashboard'
  get 'students/compexam'
  get 'students/compexam/apply' => 'students#apply', :as => :s_application

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	include SessionsHelper
	before_action :require_login, :set_cache_buster	

	def profile
		@faculty = Faculty.find(current_user.id)
	end

	def mysubjects
		@faculty = Faculty.find(current_user.id)
		@arr = Array.new
		@toffering = Offering.where("slots_taken > ?", 0).where(faculty_id: current_user.id)
		@toffering.each do |o| 
			if !@arr.include? o.schoolyear_id
				@arr << o.schoolyear_id
			end
		end
		@schoolyear = Schoolyear.where(id: @arr).sort_by &:startyr
	end

	def subjectdetails
	    @offering = Offering.find(params[:id])
	    @toff = Subject.find(@offering.subject_id).subject_code
	    @recordlog = Recordlog.where(offering_id: params[:id])
	    @schedule = Schedule.where(offering_id: params[:id]).first
	    @arr = Array.new
	    @recordlog.each do |r|
	      @arr << r.history_id
	    end

	    @arr1 = Array.new
	    @histories = History.where(id: @arr)

	    @histories.each do |h|
	      @arr1 << h.student_id
	    end

	    @students = Student.where(id: @arr1).sort_by &:s_lname
	    @tempSem = Semester.find(@offering.semester_id)
	    @tempSy = Schoolyear.find(@offering.schoolyear_id)
	    @tempSubj = Subject.find(@offering.subject_id)
	    @tempFacul = Faculty.find(@offering.faculty_id)
	    @sched = Schedule.find_by(offering_id: @offering.id)
	    respond_to do |format|
	      format.html
	      format.pdf do
	        pdf = ClasslistPdf.new(@offering, @students)
	        send_data pdf.render, filename: "#{@toff}_#{@offering.section}.pdf",
	                              type: "application/pdf",
	                              disposition: "inline"
	      end
	        format.xlsx {
	          response.headers['Content-Disposition'] = 'attachment; filename="Classlist.xlsx"'
	        }
	    end
	end
	def compexam
		@compexamsubjs = Compexamsubj.where(examiner: current_user.id)
		@cexam = Array.new
		@compexamsubjs.each do |c|
			@cexam << c.compexam_id
		end
		@compexam = Compexam.where(id: @cexam).sort_by &:date_applied
	end
	def edit_subj
		@compexamsubj = Compexamsubj.find(params[:id])
		@offering = Offering.find(@compexamsubj.offering_id)
		@subject = Subject.find(@offering.subject_id)
		respond_to do |format|
			format.html
			format.js
		end
	end

	def update_subj
	    @compexamsubj = Compexamsubj.find(params[:id])
	    @compexamsubj.update_attributes(:passed => params[:compexamsubj][:passed])
	    @compexamsubj.update_attributes(:id => params[:id])
	    @compexamsubj.save
	end

	def edit_password
		@teacher = Faculty.find(current_user.id)
	end

	def update_password
		@teacher = Faculty.find(current_user.id)
		user = Faculty.find(current_user.id).try(:authenticate, params[:current_password])
		if user && @teacher.update_attributes(faculty_params)
			@teacher.save!
		    redirect_to '/teachers/dashboard'
		    gflash success: "Password updated"
		else
			redirect_to '/teachers/edit_password'
		end
	end

	private

	def faculty_params
		params.require(:faculty).permit(:password, :password_confirmation)
	end

  	def require_login
    	unless logged_in?
	      	flash[:error] = "Please log in to proceed"
	      	redirect_to login_url
	    	end
 	 end

  	def set_cache_buster
    	response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    	response.headers["Pragma"] = "no-cache"
    	response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  	end 	
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_edit_subj.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 id="myModalLabel">Update Result</h2>
		</div>
		<%= form_for(@compexamsubj, :url => update_subj_path(:id => params[:id]), :html => {:class => "form-horizontal"}) do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.label :date, "Subject", class: "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= @subject.subject_code %>- <%= @subject.subject_title %>
					</div>
				</div>
				<div class="form-group">
					<%= f.label :pass, "Verdict", class: "col-sm-2 control-label" %>
					<div class="col-sm-5">
						<%= f.label :pa, "Pass" %>
						<%= f.radio_button :passed, "1" %>
					</div>
					<div class="col-sm-5">
						<%= f.label :fail, "Fail" %>
						<%= f.radio_button :passed, "0" %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-sm-6 col-sm-offset-3">

					<button type="button" class="btn btn-default btn-primary btn-block" data-toggle="modal" data-target="#promptSubmit">
						Update
					</button>

					<div class="modal fade" id="promptSubmit" role="dialog">
					    <div class="modal-dialog">
					      <div class="modal-content">
					        <div class="modal-body">
										<div class="row">
											<div class="col-md-8">
												<p>Are you sure you want to update the result?</p>
											</div>
											<div class="col-md-4">
												<button type="button" class="btn btn-default btn-sm pull-right" data-dismiss="modal">NO</button>
												<center><%= f.submit "YES", class: "btn btn-default btn-sm btn-success", id: "submitform" %></center>
											</div>
										</div>
					        </div>
					      </div>
					    </div>
					</div>

				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/teachers/compexam.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-check"></span>Manage Exam/s
                </li>
            </ol>
            <center>
            </center>
            <div class="panel-heading">
                Comprehensive Exam
            </div>
            <div class="panel-body">
              <table id="" class="table table-bordered">
                <thead>
                  <tr>
                    <th>Student ID</th>
                    <th>Name</th>
                    <th>Subject Code</th>
                    <th>Title</th>
                    <th>Result</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% @compexam.each do |ce| %>
                    <% @ces = Compexamsubj.where(examiner: current_user.id).where(compexam_id: ce.id) %>
                    <% @student = Student.find(ce.student_id) %>
                    <% @fname = @student.s_fname.upcase %>
                    <% @mname = @student.s_mname[0] %>
                    <% @lname = @student.s_lname.upcase %>
                      <% @ces.each do |ces| %>
                        <% @offering = Offering.find(ces.offering_id).subject_id %>
                        <% @subject = Subject.find(@offering) %>
                        <tr>
                          <td><%= @student.stud_id %></td>
                          <td><%= @lname %>, <%= @fname %> <%= @mname %>.</td>
                          <td><%= @subject.subject_code %></td>
                          <td><%= @subject.subject_title %></td>
                          <td>
                            <% if ces.passed == true %>
                                <% @verd = "PASSED" %>
                                <span class="label label-success">PASSED</span>
                            <% elsif ces.passed == false %>
                                <% @verd = "FAILED" %>
                                <span class="label label-danger">FAILED</span>
                            <% else %>
                                <span class="label label-warning">PENDING</span>
                            <% end %> 
                          </td>
                          <td>
                              <%= link_to edit_subj_path(:id => ces.id), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#edit_subj', :class => 'btn btn-warning btn-sm'} do %>
                                    <span class="glyphicon glyphicon-pencil"></span>
                              <% end %>
                          </td>
                        </tr>
                      <% end %>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>

        <!-- /.col-lg-12 -->
    </div>
</div>
<div id="edit_subj" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/teachers/dashboard.html.erb

<div id="page-wrapper">
    <div class="row">
      <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Dashboard
                </li>
            </ol>
        <div class="row">
          <div class="col-md-12">
          <div id="myCarousel" class="carousel slide">
            <!-- Carousel indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

                <!-- Carousel items -->
                <div class="carousel-inner">
                        <div class="active item">
                              <%=  link_to image_tag("carousel1.jpg", :alt => "Slide1", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                        <div class="item">
                              <%=  link_to image_tag("carousel2.jpg", :alt => "Slide2", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                        <div class="item">
                              <%=  link_to image_tag("carousel3.jpg", :alt => "Slide3", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                        <div class="item">
                              <%=  link_to image_tag("carousel4.jpg", :alt => "Slide4", :size => "2000x576", :crop => ":fill"), {:class => "img-responsive", :alt => "Responsive image"} %>
                        </div>
                </div>
                <!-- Carousel nav -->
                <a class="carousel-control left" href="#myCarousel" data-slide="prev"></a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next"></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(function(){
  $('#myCarousel').carousel('cycle');
});
</script>

app/views/teachers/edit_password.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Dashboard
                </li>
                <li class = "">
                    <span class="glyphicon glyphicon-th"></span>Change Password
                </li>
            </ol>
            <div class="row">
                <div class="col-md-9">
                    <div class="panel-heading custompanel">
                      <h4 class="semibold nm">CHANGE PASSWORD</h4>
                    </div>
                    <div class="panel-body">
                        <%= form_for(@teacher, :url => update_passwordt_path) do |f| %>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "Old Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= password_field_tag :current_password, params[:current_password] %>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "New Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= f.password_field :password %>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-4">
                                  <%= f.label :username, "Confirm Password" %>
                              </div>
                              <div class="col-sm-8">
                                <%= f.password_field :password_confirmation %>
                              </div>
                          </div>
                            <div class="col-sm-6">
                              <%= f.submit "Update Password", class: "btn btn-info btm-sm" %>
                            </div>
                        <% end %>                        
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

app/views/teachers/edit_subj.js.erb
$(document).ready( function() {
	$("#edit_subj").html("<%= escape_javascript(render 'teachers/edit_subj') %>");
	$('#edit_program').modal('show');
});

$("#submitform").click( function() {
  $( '#edit_subj' ).modal( 'hide' );
});

$('#edit_subj').on('hidden.bs.modal', function () {
	setTimeout('history.go(0);');
})

app/views/teachers/mysubjects.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-book"></span>My Subjects
                </li>
            </ol>
            <div class="panel-default panel container-fluid">
                    <div class="panel-heading row panel-custom">
                      <div class="col-xs-4">
                          <h3 class="panel-title">
                              My Subjects
                          </h3>
                      </div>
                      <div class="col-xs-4"></div>                                             
            </div>
            <div class="panel-body">
                <% @schoolyear.each do |s|  %>
                    <% @offering = Offering.where(schoolyear_id: s.id).where(faculty_id: current_user.id).where("slots_taken > ?", 0) %>
                    <div class="panel-heading">
                        <div style="font-weight: bold!important">
                            <b>School Year <%= s.startyr %>-<%= s.endyear %></b>
                        </div>
                    </div>
                    <table class="table display table-bordered">
                      <thead>
                        <tr>
                            <th>SUBJECT CODE</th>
                            <th>SUBJECT TITLE</th>
                            <th>SECTION</th>
                            <th>UNITS</th>
                            <th>TIME/DAYS</th>
                            <th>SEMESTER</th>
                            <th>CLASS SIZE</th>
                            <th>ACTION</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @offering.each do |o| %>
                            <% @subjectC = Subject.find(o.subject_id).subject_code %>
                            <% @subjectT = Subject.find(o.subject_id).subject_title %>
                            <% @sch = Schedule.find_by(offering_id: o.id) %>
                            <% @tempday = @sch.days.gsub(/[",0]/,'') %>
                            <% @tempday1 = @tempday.gsub(/"|\[|\]/, '') %>
                            <% @days = @tempday1.delete(' ') %>
                            <% @timestart = @sch.time_start.strftime("%I:%M %p") %>
                            <% @c = " - " %>
                            <% @timeend = @sch.time_end.strftime("%I:%M %p") %>
                            <% @sem = Semester.find(o.semester_id).sem_name %>
                            <% @sy = Schoolyear.find(o.schoolyear_id) %>
                            <% @tempSy = @sy.startyr.to_s + "-" + @sy.endyear.to_s %> 

                            <tr>
                                <td><%= @subjectC %></td>
                                <td><%= @subjectT %></td>
                                <td><%= o.section %></td>
                                <td><%= o.unit %></td>
                                <td><%= @timestart %>-<%= @timeend %> <%= @days %></td>
                                <td><%= @sem %></td>
                                <td style="text-align: center"><%= o.slots_taken %></td>
                                <td>
                                        <a href="/teachers/mysubjects/<%= o.id %>" class="btn btn-sm btn-primary">
                                            <span class="glyphicon glyphicon-info-sign"></span>
                                        </a>

                                </td>
                            </tr>
                        <% end %>
                      </tbody>
                    </table>
                <% end %>
            </div>
        </div>

        <!-- /.col-lg-12 -->
    </div>
</div>

app/views/teachers/profile.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-2">
          <!-- filler -->
        </div>
        <div class="col-md-10">
            <ol class="breadcrumb">
                <li class = "active">
                    <span class="glyphicon glyphicon-dashboard"></span>Dashboard
                </li>
                <li class = "">
                    <span class="glyphicon glyphicon-th"></span>Profile
                </li>
            </ol>
            <div class="row">
                <div class="col-md-9">
                    <div class="panel-heading custompanel">
                      <h4 class="semibold nm">FACULTY PROFILE</h4>
                    </div>
                    <div class="panel-body"> 
                        <div class="form-group">
                            <div class="col-sm-4">
                                Faculty ID
                            </div>
                            <div class="col-sm-8">
                                <%= @faculty.f_id %>
                            </div>
                        </div>  
                        <div class="form-group">
                            <div class="col-sm-4">
                                Name
                            </div>
                            <div class="col-sm-8">
                              <%= @faculty.f_fname %> <%= @faculty.f_mname[0] %>. <%= @faculty.f_lname %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                              Degree
                            </div>
                            <div class="col-sm-8">
                              <%= @faculty.degree %>
                            </div>
                        </div>                    
                        <div class="form-group">
                            <div class="col-sm-4">
                              Employee Type
                            </div>
                            <div class="col-sm-8">
                              <%= @faculty.f_type %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>